// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Decode(arg1:string):Promise<string>;

export function Base64Encode(arg1:string):Promise<string>;

export function GenerateUUID():Promise<string>;

export function NormalizeUUID(arg1:string):Promise<string>;

export function URLDecode(arg1:string):Promise<string>;

export function URLEncode(arg1:string):Promise<string>;
