// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Decode(arg1) {
  return window['go']['utils']['Encoding']['Base64Decode'](arg1);
}

export function Base64Encode(arg1) {
  return window['go']['utils']['Encoding']['Base64Encode'](arg1);
}

export function GenerateUUID() {
  return window['go']['utils']['Encoding']['GenerateUUID']();
}

export function NormalizeUUID(arg1) {
  return window['go']['utils']['Encoding']['NormalizeUUID'](arg1);
}

export function URLDecode(arg1) {
  return window['go']['utils']['Encoding']['URLDecode'](arg1);
}

export function URLEncode(arg1) {
  return window['go']['utils']['Encoding']['URLEncode'](arg1);
}
