// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compress(arg1) {
  return window['go']['utils']['Json']['Compress'](arg1);
}

export function DecodeUnicode(arg1) {
  return window['go']['utils']['Json']['DecodeUnicode'](arg1);
}

export function EncodeUnicode(arg1) {
  return window['go']['utils']['Json']['EncodeUnicode'](arg1);
}

export function Escape(arg1) {
  return window['go']['utils']['Json']['Escape'](arg1);
}

export function Format(arg1) {
  return window['go']['utils']['Json']['Format'](arg1);
}

export function Unescape(arg1) {
  return window['go']['utils']['Json']['Unescape'](arg1);
}
