// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compress(arg1:string):Promise<string>;

export function DecodeUnicode(arg1:string):Promise<string>;

export function EncodeUnicode(arg1:string):Promise<string>;

export function Escape(arg1:string):Promise<string>;

export function Format(arg1:string):Promise<string>;

export function Unescape(arg1:string):Promise<string>;
