// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DateTimeToMilliseconds(arg1) {
  return window['go']['utils']['Timestamp']['DateTimeToMilliseconds'](arg1);
}

export function DateTimeToSeconds(arg1) {
  return window['go']['utils']['Timestamp']['DateTimeToSeconds'](arg1);
}

export function MillisecondsToDateTime(arg1) {
  return window['go']['utils']['Timestamp']['MillisecondsToDateTime'](arg1);
}

export function NowMilliseconds() {
  return window['go']['utils']['Timestamp']['NowMilliseconds']();
}

export function NowSeconds() {
  return window['go']['utils']['Timestamp']['NowSeconds']();
}

export function SecondsToDateTime(arg1) {
  return window['go']['utils']['Timestamp']['SecondsToDateTime'](arg1);
}
