// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DateTimeToMilliseconds(arg1:string):Promise<string>;

export function DateTimeToSeconds(arg1:string):Promise<string>;

export function MillisecondsToDateTime(arg1:string):Promise<string>;

export function NowMilliseconds():Promise<string>;

export function NowSeconds():Promise<string>;

export function SecondsToDateTime(arg1:string):Promise<string>;
